packages:
  - packages/*


ignoredBuiltDependencies:
  - protobufjs
  - unrs-resolver

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@pulumi/docker'
  - '@pulumi/docker-build'
  - '@pulumi/synced-folder'
  - esbuild
