packages:
  - packages/*

allowBuilds:
  '@parcel/watcher': true
  '@pulumi/docker': true
  '@pulumi/docker-build': true
  '@pulumi/synced-folder': true
  esbuild: true
  protobufjs: false
  unrs-resolver: true
