config:
  aws:region: us-east-2
  aws:profile: home
  aws.accountId: "699040795025"
  schierer.org:domainName: schierer.org
  schierer.org:rootDomainName: schierer.org
  schierer.org:createHostedZone: false
  schierer.org:logRetentionDays: 3
  schierer.org:mojoLogLevel: warn
  schierer.org:githubOwner: lschierer
  schierer.org:githubRepo: RUT
