config:
  aws:region: us-east-2
  aws:profile: home
  schierer.org:domainName: schierer.org
  schierer.org:rootDomainName: schierer.org
  schierer.org:createHostedZone: false
  schierer.org:logRetentionDays: 30
  schierer.org:mojoLogLevel: warn
